type objectOptions = {
  [key: string]: string
}

// TODO: explanation for keys inside [] in ROMs 
// TODO: assign extensions to cores

export const LABEL_DISPLAY_MODES: objectOptions = {
  "0": "Show Full Labels",
  "1": "Remove () Content",
  "2": "Remove [] Content",
  "3": "Remove () and []",
  "4": "Keep Region",
  "5": "Keep Disc Index",
  "6": "Keep Region and Disc Index"
}

export const THUMBNAIL_MODES: objectOptions = {
  "0": "System Default",
  "1": "Off",
  "2": "Screenshot",
  "3": "Title screen",
  "4": "Boxart"
}

export const SORT_MODES: objectOptions = {
  "0": "System Default",
  "1": "Alphabetical",
  "2": "None"
}

export const CORES: objectOptions = {
  cap32_libretro: "CPC (Caprice32)",
  crocods_libretro: "CPC/GX4000 (CrocoDS)",
  fbalpha2012_cps1_libretro: "Arcade (FB Alpha 2012 CPS-1)",
  fbalpha2012_cps2_libretro: "Arcade (FB Alpha 2012 CPS-2)",
  fbalpha2012_cps3_libretro: "Arcade (FB Alpha 2012 CPS-3)",
  fbalpha2012_neogeo_libretro: "Arcade (FB Alpha 2012 Neo Geo)",
  fbalpha2012_libretro: "Arcade (FB Alpha 2012)",
  fbalpha_libretro: "Arcade (FinalBurn Alpha)",
  fbneo_libretro: "Arcade (FinalBurn Neo)",
  mame2000_libretro: "Arcade (MAME 2000)",
  mame2003_libretro: "Arcade (MAME 2003)",
  mame2003_midway_libretro: "Arcade (MAME 2003 Midway)",
  mame2003_plus_libretro: "Arcade (MAME 2003-Plus)",
  mame2010_libretro: "Arcade (MAME 2010)",
  mame_libretro: "Arcade (MAME - Current)",
  stella_libretro: "2600 (Stella)",
  stella2014_libretro: "2600 (Stella 2014)",
  a5200_libretro: "5200 (a5200)",
  atari800_libretro: "5200 (Atari800)",
  prosystem_libretro: "7800 (ProSystem)",
  virtualjaguar_libretro: "Jaguar (Virtual Jaguar)",
  mednafen_lynx_libretro: "Lynx (Beetle Lynx)",
  handy_libretro: "Lynx (Handy)",
  hatari_libretro: "ST/STE/TT/Falcon (Hatari)",
  mednafen_wswan_libretro: "WonderSwan/Color (Beetle Cygne)",
  gearcoleco_libretro: "ColecoVision (Gearcoleco)",
  puae_libretro: "Amiga (PUAE)",
  uae4arm_libretro: "Amiga (UAE4ARM)",
  vice_x128_libretro: "C128 (VICE x128)",
  frodo_libretro: "C64 (Frodo)",
  vice_x64_libretro: "C64 (VICE x64, fast)",
  vice_x64sc_libretro: "C64 (VICE x64, accurate)",
  vice_xcbm2_libretro: "CBM-II 6x0/7x0 (VICE xcbm2)",
  vice_xpet_libretro: "PET (VICE xpet)",
  vice_xplus4_libretro: "PLUS/4 (VICE xplus4)",
  vice_xvic_libretro: "VIC-20 (VICE xvic)",
  dosbox_core_libretro: "DOS (DOSBox-core)",
  dosbox_pure_libretro: "DOS (DOSBox-Pure)",
  dosbox_svn_libretro: "DOS (DOSBox-SVN)",
  fmsx_libretro: "MSX (fMSX)",
  bluemsx_libretro: "MSX/SVI/ColecoVision/SG-1000 (blueMSX)",
  mednafen_pce_libretro: "PC Engine / SuperGrafx / CD (Beetle PCE)",
  mednafen_pce_fast_libretro: "PC Engine / CD (Beetle PCE FAST)",
  mednafen_supergrafx_libretro: "PC Engine SuperGrafx (Beetle SuperGrafx)",
  quasi88_libretro: "PC-8000 / PC-8800 series (QUASI88)",
  nekop2_libretro: "PC-98 (Neko Project II)",
  np2kai_libretro: "PC-98 (Neko Project II Kai)",
  mednafen_pcfx_libretro: "PC-FX (Beetle PC-FX)",
  citra_libretro: "3DS (Citra)",
  citra2018_libretro: "3DS (Citra 2018)",
  citra_canary_libretro: "3DS (Citra Canary/Experimental)",
  desmume_libretro: "DS (DeSmuME)",
  desmume2015_libretro: "DS (DeSmuME 2015)",
  melonds_libretro: "DS (melonDS)",
  gambatte_libretro: "Game Boy / Color (Gambatte)",
  gearboy_libretro: "Game Boy / Color (Gearboy)",
  sameboy_libretro: "Game Boy / Color (SameBoy)",
  tgbdual_libretro: "Game Boy / Color (TGB Dual)",
  gpsp_libretro: "Game Boy Advance (gpSP)",
  mgba_libretro: "Game Boy Advance (mGBA)",
  vba_next_libretro: "Game Boy Advance (VBA Next)",
  vbam_libretro: "Game Boy Advance (VBA-M)",
  dolphin_libretro: "GameCube / Wii (Dolphin)",
  ishiiruka_libretro: "GameCube / Wii (Ishiiruka)",
  fceumm_libretro: "NES / Famicom (FCEUmm)",
  mesen_libretro: "NES / Famicom (Mesen)",
  nestopia_libretro: "NES / Famicom (Nestopia UE)",
  quicknes_libretro: "NES / Famicom (QuickNES)",
  mupen64plus_next_libretro: "Nintendo 64 (Mupen64Plus-Next)",
  mupen64plus_next_gles3_libretro: "Nintendo 64 (Mupen64Plus-Next GLES3)",
  parallel_n64_libretro: "Nintendo 64 (ParaLLel N64)",
  pokemini_libretro: "Pokemon Mini (PokeMini)",
  bsnes2014_accuracy_libretro: "SNES / SFC (bsnes 2014 Accuracy)",
  bsnes2014_balanced_libretro: "SNES / SFC (bsnes 2014 Balanced)",
  bsnes2014_performance_libretro: "SNES / SFC (bsnes 2014 Performance)",
  bsnes_libretro: "SNES / SFC (bsnes)",
  bsnes_accuracy_libretro: "SNES / SFC (bsnes Accuracy)",
  bsnes_balanced_libretro: "SNES / SFC (bsnes Balanced)",
  bsnes_performance_libretro: "SNES / SFC (bsnes Performance)",
  bsnes_hd_beta_libretro: "SNES / SFC (bsnes-hd beta)",
  bsnes_mercury_accuracy_libretro: "SNES / SFC (bsnes-mercury Accuracy)",
  bsnes_mercury_balanced_libretro: "SNES / SFC (bsnes-mercury Balanced)",
  bsnes_mercury_performance_libretro: "SNES / SFC (bsnes-mercury Performance)",
  snes9x_libretro: "SNES / SFC (Snes9x - Current)",
  snes9x2002_libretro: "SNES / SFC (Snes9x 2002)",
  snes9x2005_libretro: "SNES / SFC (Snes9x 2005)",
  snes9x2005_plus_libretro: "SNES / SFC (Snes9x 2005 Plus)",
  snes9x2010_libretro: "SNES / SFC (Snes9x 2010)",
  "mesen-s_libretro": "SNES / SFC / Game Boy / Color (Mesen-S)",
  mednafen_vb_libretro: "Virtual Boy (Beetle VB)",
  flycast_libretro: "Dreamcast/NAOMI (Flycast)",
  blastem_libretro: "Mega Drive - Genesis (BlastEm)",
  smsplus_libretro: "MS/GG (SMS Plus GX)",
  genesis_plus_gx_libretro: "MS/GG/MD/CD (Genesis Plus GX)",
  genesis_plus_gx_wide_libretro: "MS/GG/MD/CD (Genesis Plus GX (Widescreen Mod))",
  picodrive_libretro: "MS/GG/MD/CD/32x (Picodrive)",
  gearsystem_libretro: "MS/GG/SG-1000 (Gearsystem)",
  mednafen_saturn_libretro: "Saturn (Beetle Saturn)",
  yabanshiro_libretro: "Saturn (YabaSanshiro)",
  yabause_libretro: "Saturn (Yabause)",
  kronos_libretro: "Saturn/ST-V (Kronos)",
  px68k_libretro: "X68000 (PX68k)",
  x1_libretro: "Sharp X1 (X Millenium)",
  "81_libretro": "ZX 81 (EightyOne)",
  fuse_libretro: "ZX Spectrum (Fuse)",
  neocd_libretro: "Neo Geo CD (Neo CD)",
  mednafen_ngp_libretro: "Neo Geo Pocket / Color (Beetle NeoPop)",
  race_libretro: "Neo Geo Pocket / Color (RACE)",
  mednafen_psx_libretro: "PlayStation (Beetle PSX)",
  mednafen_psx_hw_libretro: "PlayStation (Beetle PSX HW)",
  pcsx_rearmed_libretro: "PlayStation (PCSX ReARMed)",
  swanstation_libretro: "PlayStation (SwanStation)",
  pcsx2_libretro: "PlayStation 2 (PCSX2)",
  play_libretro: "PlayStation 2 (Play!)",
  ppsspp_libretro: "PlayStation Portable (PPSSPP)",
  opera_libretro: "The 3DO Company - 4DO (Opera)",
  nxengine_libretro: "Cave Story (NXEngine)",
  jaxe_libretro: "CHIP-8/S-CHIP/XO-CHIP (JAXE)",
  prboom_libretro: "Doom (PrBoom)",
  boom3_libretro: "Doom 3 (boom3)",
  boom3_xp_libretro: "Doom 3: Resurrection of Evil (boom 3 xp)",
  reminiscence_libretro: "Flashback (REminiscence)",
  jumpnbump_libretro: "Jump 'n Bump",
  gme_libretro: "Game Music Emu",
  vecx_libretro: "Vectrex (vecx)",
  gw_libretro: "Handheld Electronic (GW)",
  squirreljme_libretro: "Java ME (SquirrelJME)",
  o2em_libretro: "Odyssey2 / Phillips Videopac+ (O2EM)",
  freeintv_libretro: "Intellivision (FreeIntv)",
  retro8_libretro: "PICO-8 (Retro8)",
  tyrquake_libretro: "Quake (TyrQuake)",
  vitaquake2_libretro: "Quake II (vitaQuake 2)",
  vitaquake3_libretro: "Quake III (vitaQuake 3)",
  xrick_libretro: "Rick Dangerous (XRick)",
  easyrpg_libretro: "RPG Maker 2000/2003 (EasyRPG)",
  scummvm_libretro: "ScummVM",
};


export const DATABASES = [
  ["DETECT", [""]],
  ["Amstrad - CPC.lpl", ["dsk"]],
  ["Atari - 2600.lpl", ["a26"]],
  ["Atari - 5200.lpl", ["a52"]],
  ["Atari - 7800.lpl", ["a78"]],
  ["Atari - Jaguar.lpl", ["j64"]],
  ["Atari - Lynx.lpl", ["lnx"]],
  ["Atari - ST.lpl", ["ipf"]],
  ["Bandai - WonderSwan.lpl", ["ws"]],
  ["Bandai - WonderSwan Color.lpl", ["wsc"]],
  ["Cannonball.lpl", ["bin"]],
  ["Casio - Loopy.lpl", ["bin"]], 
  ["Casio - PV-1000.lpl", ["bin"]], 
  ["Coleco - ColecoVision.lpl", ["col", "rom"]],
  ["Commodore - 64.lpl", ["D64"]],
  ["Commodore - Amiga.lpl", ["adf"]],
  ["Commodore - Plus-4.lpl", [""]],
  ["Commodore - VIC-20.lpl", [""]], 
  ["DOOM.lpl", [""]],
  ["DOS.lpl", ["exe"]],
  ["Emerson - Arcadia 2001.lpl", ["bin"]],
  ["Epoch - Super Cassette Vision.lpl", ["bin"]],
  ["Fairchild - Channel F.lpl", ["bin"]],
  ["FBNeo - Arcade Games.lpl", [""]],
  ["Flashback.lpl", [""]],
  ["Funtech - Super Acan.lpl", [""]],
  ["GamePark - GP32.lpl", [""]],
  ["GCE - Vectrex.lpl", [""]],
  ["Handheld Electronic Game.lpl", [""]],
  ["Hartung - Game Master.lpl", [""]],
  ["HBMAME.lpl", [""]],
  ["Infocom - Z-Machine.lpl", [""]],
  ["Jump 'n Bump.lpl", [""]],
  ["LeapFrog - Leapster Learning Game System.lpl", [""]],
  ["LowRes NX.lpl", [""]],
  ["Lutro.lpl", [""]],
  ["Magnavox - Odyssey2.lpl", [""]],
  ["MAME.lpl", [""]],
  ["MAME 2000.lpl", [""]],
  ["MAME 2003.lpl", [""]],
  ["MAME 2003-Plus.lpl", [""]],
  ["MAME 2010.lpl", [""]],
  ["MAME 2015.lpl", [""]],
  ["MAME 2016.lpl", [""]],
  ["Mattel - Intellivision.lpl", [""]],
  ["Microsoft - MSX.lpl", [""]],
  ["Microsoft - MSX2.lpl", [""]],
  ["Microsoft - Xbox.lpl", [""]],
  ["MicroW8.lpl", [""]],
  ["MrBoom.lpl", [""]],
  ["NEC - PC Engine - TurboGrafx 16.lpl", [""]],
  ["NEC - PC Engine CD - TurboGrafx-CD.lpl", [""]],
  ["NEC - PC Engine SuperGrafx.lpl", [""]],
  ["NEC - PC-98.lpl", [""]],
  ["NEC - PC-FX.lpl", [""]],
  ["Nintendo - e-Reader.lpl", [""]],
  ["Nintendo - Family Computer Disk System.lpl", [""]],
  ["Nintendo - Game Boy.lpl", [""]],
  ["Nintendo - Game Boy Advance.lpl", [""]],
  ["Nintendo - Game Boy Color.lpl", [""]],
  ["Nintendo - GameCube.lpl", [""]],
  ["Nintendo - Nintendo 3DS.lpl", [""]],
  ["Nintendo - Nintendo 64.lpl", [""]],
  ["Nintendo - Nintendo 64DD.lpl", [""]],
  ["Nintendo - Nintendo DS.lpl", [""]],
  ["Nintendo - Nintendo DSi.lpl", [""]],
  ["Nintendo - Nintendo Entertainment System.lpl", ["nes"]],
  ["Nintendo - Pokemon Mini.lpl", [""]],
  ["Nintendo - Satellaview.lpl", [""]],
  ["Nintendo - Sufami Turbo.lpl", [""]],
  ["Nintendo - Super Nintendo Entertainment System.lpl", ["sfc"]],
  ["Nintendo - Virtual Boy.lpl", [""]],
  ["Nintendo - Wii.lpl", [""]],
  ["Nintendo - Wii (Digital).lpl", [""]],
  ["Philips - CD-i.lpl", [""]],
  ["Philips - Videopac+.lpl", [""]],
  ["PuzzleScript.lpl", [""]],
  ["Quake.lpl", [""]],
  ["Quake II.lpl", [""]],
  ["Quake III.lpl", [""]],
  ["RCA - Studio II.lpl", [""]],
  ["Rick Dangerous.lpl", [""]],
  ["RPG Maker.lpl", [""]],
  ["ScummVM.lpl", [""]],
  ["Sega - 32X.lpl", [""]],
  ["Sega - Dreamcast.lpl", [""]],
  ["Sega - Game Gear.lpl", ["gg"]],
  ["Sega - Master System - Mark III.lpl", [""]],
  ["Sega - Mega Drive - Genesis.lpl", ["md", "gen"]],
  ["Sega - Mega-CD - Sega CD.lpl", ["d88"]],
  ["Sega - Naomi.lpl", [""]],
  ["Sega - Naomi 2.lpl", [""]],
  ["Sega - PICO.lpl", [""]],
  ["Sega - Saturn.lpl", ["bin"]],
  ["Sega - SG-1000.lpl", [""]],
  ["Sharp - X1.lpl", [""]],
  ["Sharp - X68000.lpl", [""]],
  ["Sinclair - ZX 81.lpl", [""]],
  ["Sinclair - ZX Spectrum.lpl", [""]],
  ["Sinclair - ZX Spectrum +3.lpl", [""]],
  ["SNK - Neo Geo CD.lpl", [""]],
  ["SNK - Neo Geo Pocket.lpl", [""]],
  ["SNK - Neo Geo Pocket Color.lpl", [""]],
  ["Sony - PlayStation.lpl", [""]],
  ["Sony - PlayStation 2.lpl", [""]],
  ["Sony - PlayStation 3.lpl", [""]],
  ["Sony - PlayStation 3 (PSN).lpl", [""]],
  ["Sony - PlayStation Portable.lpl", [""]],
  ["Sony - PlayStation Portable (PSN).lpl", [""]],
  ["Sony - PlayStation Vita.lpl", [""]],
  ["The 3DO Company - 3DO.lpl", [""]],
  ["Thomson - MOTO.lpl", [""]],
  ["TIC-80.lpl", [""]],
  ["Tiger - Game.com.lpl", [""]],
  ["Tomb Raider.lpl", [""]],
  ["Uzebox.lpl", [""]],
  ["Vircon32.lpl", [""]],
  ["VTech - CreatiVision.lpl", [""]],
  ["VTech - V.Smile.lpl", [""]],
  ["WASM-4.lpl", [""]],
  ["Watara - Supervision.lpl", [""]]
]



const DATABASES_OLD = [
  "DETECT",
  "Amstrad - CPC",
  "Atari - 2600",
  "Atari - 5200",
  "Atari - 7800",
  "Atari - Jaguar",
  "Atari - Lynx",
  "Atari - ST",
  "Bandai - WonderSwan",
  "Bandai - WonderSwan Color",
  "Coleco - ColecoVision",
  "Commodore - 64",
  "Commodore - Amiga",
  "Commodore - Plus-4",
  "DOOM",
  "DOS",
  "FBNeo - Arcade Games",
  "GCE - Vectrex",
  "MAME",
  "MAME 2000",
  "MAME 2003",
  "MAME 2003-Plus",
  "MAME 2010",
  "Microsoft - MSX",
  "Microsoft - MSX2",
  "NEC - PC Engine - TurboGrafx 16",
  "NEC - PC Engine CD - TurboGrafx-CD",
  "NEC - PC Engine SuperGrafx",
  "NEC - PC-98",
  "NEC - PC-FX",
  "Nintendo - Family Computer Disk System",
  "Nintendo - Game Boy",
  "Nintendo - Game Boy Advance",
  "Nintendo - Game Boy Color",
  "Nintendo - GameCube",
  "Nintendo - Nintendo 3DS",
  "Nintendo - Nintendo 64",
  "Nintendo - Nintendo 64DD",
  "Nintendo - Nintendo DS",
  "Nintendo - Nintendo DSi",
  "Nintendo - Nintendo Entertainment System",
  "Nintendo - Pokemon Mini",
  "Nintendo - Satellaview",
  "Nintendo - Super Nintendo Entertainment System",
  "Nintendo - Virtual Boy",
  "Nintendo - Wii",
  "SNK - Neo Geo CD",
  "SNK - Neo Geo Pocket",
  "SNK - Neo Geo Pocket Color",
  "ScummVM",
  "Sega - 32X",
  "Sega - Dreamcast",
  "Sega - Game Gear",
  "Sega - Master System - Mark III",
  "Sega - Mega Drive - Genesis",
  "Sega - Mega-CD - Sega CD",
  "Sega - PICO",
  "Sega - SG-1000",
  "Sega - Saturn",
  "Sharp - X68000",
  "Sinclair - ZX 81",
  "Sinclair - ZX Spectrum",
  "Sinclair - ZX Spectrum +3",
  "Sony - PlayStation",
  "Sony - PlayStation 2",
  "Sony - PlayStation Portable",
  "The 3DO Company - 3DO"
]
